name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install MPI
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: 'openmpi' # [ 'mpich', 'openmpi', 'intelmpi']
    
    - name: Configure CMake
      # Configure CMake in build subdirectory.
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build the program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    
    - name: Run send example
      run: mpiexec -n 2 ${{github.workspace}}/build/send
    
    - name: Run bcast example
      run: mpiexec -n 4 ${{github.workspace}}/build/bcast

#    - name: Test
#      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
#      run: ctest -C ${{env.BUILD_TYPE}}

